### ISSUE TITLE
마이페이지 구현

### ISSUE THREAD

**Issue by Choisehyeon** [team-replace/replace-android#25]
## 📝 요약
마이페이지 구현

## 💡 Todo
- [x] 마이 페이지 뷰 구현
- [x] 커플 연결하기 페이지와 연동
- [x] 상태에 따라 보여지는 뷰 적용
- [x] 커플 연결 끊기 연동
  - [x] 다이얼로그 

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
