### ISSUE TITLE
메인페이지 지도 클릭시 서버 연동

### ISSUE THREAD

**Issue by Choisehyeon** [team-replace/replace-android#35]
## 📝 요약
메인페이지 지도 클릭 시 서버 연동

## 💡 Todo
- [x] 메인페이지 지도 클릭 시 서버 연동
  - [x] 오류 상황이 뜨는 경우 마커가 보이지 않도록 구현
  - [x] 성공적으로 오면 마커가 보이도록 구현

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
