### ISSUE TITLE
메인페이지 바텀 슬라이드 뷰 구현 및 서버 연동

### ISSUE THREAD

**Issue by Choisehyeon** [team-replace/replace-android#36]
## 📝 요약
기능 요청에 대한 간략한 설명을 작성해주세요.

## 💡 Todo
- [x] 메인 페이지 바텀 슬라이드 뷰 구현
   - [x] 바텀 슬라이드 뷰 제일 위로 올리면 toolbar에 건물 이름이 보이도록 구현
- [x] 바텀 슬라이드 뷰 서버 연동 

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
