### ISSUE TITLE
검색 페이지 뷰 구현 및 서버 연동

### ISSUE THREAD

**Issue by Choisehyeon** [team-replace/replace-android#39]
## 📝 요약
검색 페이지 구현

## 💡 Todo
- [ ] 검색 페이지 뷰 구현
- [ ] 검색 페이지 서버 연동
- [ ] 검색 리사이클러뷰 아이템 클릭시 지도에 마커 보이도록 구현

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
